# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pagoda, o.s.
email: pagoda@pagoda.cz
description: > # this means to ignore newlines until "baseurl:"
    Občanské sdružení Pagoda je nezisková organizace zaměřená
    na podporu a prezentaci deskové hry Go.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.pagoda.cz" # the base hostname & protocol for your site
adresa: "Brzická 365, 190 16 Praha 21"
ico: "22664505"
banka: "Raiffeisenbank a.s. Praha, č.ú. 2942556001 / 5500"

# Build settings
markdown: kramdown
